remote_theme: mikearnaldi/just-the-docs

baseurl: "/effect-schemas"
repository: "leonitousconforti/effect-schemas"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
"effect-schemas on GitHub":
  - "https://github.com/leonitousconforti/effect-schemas"
